# Generated by Django 5.1.6 on 2025-02-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_rename_date_task_date_created_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.CharField(blank=True, null=True),
        ),
    ]
